[app]
# Network address for the server to listen on.
address = "127.0.0.1:9000"

# The website URL to be used on the frontend pages.
root_url = "http://localhost:9000"


################################################################################


[db]
# Maximum connections.
max_conns = 100


[api_results]
# Default number of packages to return per page when paginated.
per_page = 20

# The absolute maximum number of results to return per query in case the
# per_page value above is overwritten from the frontend.
max_per_page = 50


[site_results]
# Default number of packages to show per page on the website.
per_page = 20

# The absolute maximum number of results to show per page in case the
# per_page value above is overwritten with a URL param.
max_per_page = 50


################################################################################

[import]
families = ["debuntu", "nix", "arch", "alpine", "fedora", "centos", "gentoo", "opensuse", "mageia", "openmandriva", "openwrt", "void", "solus", "slackware", "slackbuilds", "freebsd", "openbsd", "macports"]